"""Defensive, read-only parser for Urban Assault SKLT wireframe data."""

from __future__ import annotations

from dataclasses import dataclass, field
import math
from pathlib import Path
import struct
from typing import Iterable


MAX_FILE_SIZE = 512 * 1024 * 1024
MAX_FORM_DEPTH = 64
TARGET_CHUNKS = {b"POO2", b"POL2", b"SEN2", b"OTL2", b"OLPL",
                 b"POOL", b"POLY", b"SENS"}

Point3D = tuple[float, float, float]
Point2D = tuple[int, int]
Polygon = list[int]
OutlineGroup = list[int]


class SkltParseError(Exception):
    """A controlled error raised when a file cannot be opened or parsed."""


@dataclass(frozen=True)
class ChunkInfo:
    name: str
    declared_size: int
    actual_size: int
    offset: int
    payload_offset: int
    depth: int
    form_type: str = ""

    @property
    def display_name(self) -> str:
        if self.form_type:
            return f"{self.name} ({self.form_type})"
        return self.name


@dataclass
class SkltModel:
    source_name: str = ""
    original_data: bytes = b""
    poo2_payload_offset: int | None = None
    poo2_payload_size: int = 0
    pol2_payload_offset: int | None = None
    pol2_payload_size: int = 0
    otl2_payload_offset: int | None = None
    otl2_payload_size: int = 0
    points: list[Point3D] = field(default_factory=list)
    polygons: list[Polygon] = field(default_factory=list)
    sensors: list[Point3D] = field(default_factory=list)
    outline_points: list[Point2D] = field(default_factory=list)
    outline_groups: list[OutlineGroup] = field(default_factory=list)
    chunks: list[ChunkInfo] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    parsed_polygon_count: int = 0
    parsed_outline_group_count: int = 0

    @property
    def rendered_polygon_count(self) -> int:
        return sum(1 for polygon in self.polygons if len(polygon) >= 2)

    @property
    def rendered_polygon_line_count(self) -> int:
        line_count = 0
        for polygon in self.polygons:
            if len(polygon) == 2:
                line_count += 1
            elif len(polygon) > 2:
                line_count += len(polygon)
        return line_count

    @property
    def rendered_outline_group_count(self) -> int:
        return len(self.outline_groups)

    @property
    def rendered_outline_line_count(self) -> int:
        line_count = 0
        for group in self.outline_groups:
            if len(group) == 2:
                line_count += 1
            elif len(group) > 2:
                line_count += len(group)
        return line_count

    @property
    def has_outline_data(self) -> bool:
        return bool(self.outline_points and self.outline_groups)


def parse_sklt_file(path: str | Path) -> SkltModel:
    """Read an SKLT file without modifying it and return its parsed model."""

    file_path = Path(path)
    try:
        file_size = file_path.stat().st_size
        if file_size > MAX_FILE_SIZE:
            raise SkltParseError(
                f"File is too large ({file_size} bytes; limit is {MAX_FILE_SIZE})."
            )
        with file_path.open("rb") as source:
            data = source.read()
    except OSError as exc:
        raise SkltParseError(f"Could not open file: {exc}") from exc

    return parse_sklt_bytes(data, file_path.name)


def create_minimal_sklt_model(source_name: str = "Untitled.SKL") -> SkltModel:
    """Create a tiny editable SKLT model with one POO2 vertex at the origin.

    This is used by File -> New.  The generated byte stream intentionally keeps
    the normal FORM/SKLT + POO2/POL2 layout so the existing structural saver can
    write it back with more vertices and links later.
    """

    poo2_payload = _encode_poo2([(0.0, 0.0, 0.0)])
    pol2_payload = _encode_pol2([], 1)
    children = (
        b"POO2" + struct.pack(">I", len(poo2_payload)) + poo2_payload
        + (b"\0" if len(poo2_payload) & 1 else b"")
        + b"POL2" + struct.pack(">I", len(pol2_payload)) + pol2_payload
        + (b"\0" if len(pol2_payload) & 1 else b"")
    )
    form_payload = b"SKLT" + children
    data = b"FORM" + struct.pack(">I", len(form_payload)) + form_payload
    return parse_sklt_bytes(data, source_name)


def parse_sklt_bytes(data: bytes, source_name: str = "<memory>") -> SkltModel:
    """Parse an SKLT byte stream defensively.

    SKLT uses an IFF-style layout. Each chunk has a four-byte ID, a big-endian
    uint32 payload size, its payload, and an optional padding byte for odd sizes.
    A FORM payload begins with a four-byte form type followed by child chunks.
    """

    model = SkltModel(source_name=source_name, original_data=data)
    payloads: dict[bytes, list[tuple[bytes, int, int]]] = {
        chunk_id: [] for chunk_id in TARGET_CHUNKS
    }

    if not data:
        model.warnings.append("The file is empty.")
        return model

    if data[:4] != b"FORM":
        model.warnings.append("The file does not begin with a FORM chunk.")

    _parse_chunk_stream(
        data=data,
        start=0,
        end=len(data),
        depth=0,
        model=model,
        payloads=payloads,
    )

    if not any(chunk.form_type == "SKLT" for chunk in model.chunks):
        model.warnings.append("No FORM (SKLT) container was detected.")

    poo2_payload = _first_payload(payloads, b"POO2", model)
    pol2_payload = _first_payload(payloads, b"POL2", model)
    sen2_payload = _first_payload(payloads, b"SEN2", model)
    otl2_payload = _first_payload(payloads, b"OTL2", model)
    olpl_payload = _first_payload(payloads, b"OLPL", model)
    # Legacy v1 chunks (old dev-CD skeletons): POOL/SENS are 3 x int16 BE per
    # point, POLY is an int16 index stream where -1 ends each polygon.  The
    # engine still loads them (sklt.cpp); OpenUAStudio reads them for display but
    # keeps editing/saving restricted to the v2 chunks.
    pool_payload = _first_payload(payloads, b"POOL", model)
    poly_payload = _first_payload(payloads, b"POLY", model)
    sens_payload = _first_payload(payloads, b"SENS", model)

    if poo2_payload is not None:
        model.poo2_payload_offset = poo2_payload[1]
        model.poo2_payload_size = poo2_payload[2]
        model.points = _parse_point_chunk(poo2_payload[0], "POO2", model.warnings)
    elif pool_payload is not None:
        model.points = _parse_legacy_point_chunk(
            pool_payload[0], "POOL", model.warnings
        )
        model.warnings.append(
            "Legacy v1 POOL chunk: displayed read-only (saving requires POO2)."
        )
    else:
        model.warnings.append("No POO2 chunk was found.")

    if sen2_payload is not None:
        model.sensors = _parse_point_chunk(sen2_payload[0], "SEN2", model.warnings)
    elif sens_payload is not None:
        model.sensors = _parse_legacy_point_chunk(
            sens_payload[0], "SENS", model.warnings
        )

    if pol2_payload is not None:
        model.pol2_payload_offset = pol2_payload[1]
        model.pol2_payload_size = pol2_payload[2]
        raw_polygons = _parse_pol2(pol2_payload[0], model.warnings)
        model.parsed_polygon_count = len(raw_polygons)
        model.polygons = _validate_polygons(raw_polygons, len(model.points), model.warnings)
    elif poly_payload is not None:
        raw_polygons = _parse_legacy_poly(poly_payload[0], model.warnings)
        model.parsed_polygon_count = len(raw_polygons)
        model.polygons = _validate_polygons(raw_polygons, len(model.points), model.warnings)
        model.warnings.append(
            "Legacy v1 POLY chunk: displayed read-only (saving requires POL2)."
        )
    else:
        model.warnings.append("No POL2 chunk was found.")

    if otl2_payload is not None:
        model.otl2_payload_offset = otl2_payload[1]
        model.otl2_payload_size = otl2_payload[2]
        model.outline_points = _parse_otl2(otl2_payload[0], model.warnings)

    if olpl_payload is not None:
        raw_outline_groups = _parse_olpl(olpl_payload[0], model.warnings)
        model.parsed_outline_group_count = len(raw_outline_groups)
        model.outline_groups = _validate_outline_groups(
            raw_outline_groups, len(model.outline_points), model.warnings
        )
    elif otl2_payload is not None:
        model.warnings.append("OTL2 was found, but OLPL was not found.")

    if olpl_payload is not None and otl2_payload is None:
        model.warnings.append("OLPL was found, but OTL2 was not found.")

    return model


def save_sklt_with_otl2_points(
    model: SkltModel, points: list[Point2D], output_path: str | Path
) -> Path | None:
    """Save a copy of the original file with only OTL2 coordinates changed.

    The OTL2 payload is fixed-size byte pairs, so changing point coordinates
    never changes chunk size or layout. Every other byte is preserved.
    Returns None. Existing output files are overwritten directly.
    """

    if model.otl2_payload_offset is None or model.otl2_payload_size <= 0:
        raise SkltParseError("This file has no OTL2 chunk to save.")

    if len(points) * 2 != model.otl2_payload_size:
        raise SkltParseError(
            "OTL2 point count changed; refusing to save because the chunk size "
            "must stay unchanged."
        )

    edited = bytearray(model.original_data)
    payload_offset = model.otl2_payload_offset
    for index, (x, y) in enumerate(points):
        edited[payload_offset + index * 2] = _clamp_byte(x)
        edited[payload_offset + index * 2 + 1] = _clamp_byte(y)

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)

    try:
        with destination.open("wb") as target:
            target.write(edited)
    except OSError as exc:
        raise SkltParseError(f"Could not save file: {exc}") from exc

    return None


def save_sklt_with_poo2_points(
    model: SkltModel, points: list[Point3D], output_path: str | Path
) -> Path | None:
    """Save a copy of the original file with only POO2 coordinates changed."""

    if model.poo2_payload_offset is None or model.poo2_payload_size <= 0:
        raise SkltParseError("This file has no POO2 chunk to save.")

    if len(points) * 12 != model.poo2_payload_size:
        raise SkltParseError(
            "POO2 point count changed; refusing to save because the chunk size "
            "must stay unchanged."
        )

    edited = bytearray(model.original_data)
    payload_offset = model.poo2_payload_offset
    for index, point in enumerate(points):
        x, y, z = point
        if not all(math.isfinite(value) for value in (x, y, z)):
            raise SkltParseError("POO2 coordinates must be finite float values.")
        struct.pack_into(">fff", edited, payload_offset + index * 12, x, y, z)

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)

    try:
        with destination.open("wb") as target:
            target.write(edited)
    except OSError as exc:
        raise SkltParseError(f"Could not save file: {exc}") from exc

    return None


def save_sklt_with_poo2_pol2_structure(
    model: SkltModel,
    points: list[Point3D],
    polygons: list[Polygon],
    output_path: str | Path,
) -> Path | None:
    """Save a structurally changed POO2/POL2 model.

    This path is used when vertices are added or deleted, so chunk sizes and
    surrounding FORM sizes may change. It replaces only the first POO2 and POL2
    payloads and preserves chunk order and unrelated payloads.
    """

    if model.poo2_payload_offset is None or model.poo2_payload_size <= 0:
        raise SkltParseError("This file has no POO2 chunk to save.")
    if model.pol2_payload_offset is None or model.pol2_payload_size <= 0:
        raise SkltParseError("This file has no POL2 chunk to save.")

    replacements = {
        b"POO2": _encode_poo2(points),
        b"POL2": _encode_pol2(polygons, len(points)),
    }
    edited = _rewrite_first_chunk_payloads(model.original_data, replacements)

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)

    try:
        with destination.open("wb") as target:
            target.write(edited)
    except OSError as exc:
        raise SkltParseError(f"Could not save file: {exc}") from exc

    return None


def _parse_chunk_stream(
    data: bytes,
    start: int,
    end: int,
    depth: int,
    model: SkltModel,
    payloads: dict[bytes, list[tuple[bytes, int, int]]],
) -> None:
    if depth > MAX_FORM_DEPTH:
        model.warnings.append(
            f"FORM nesting exceeds the safe limit of {MAX_FORM_DEPTH}; "
            "deeper chunks were ignored."
        )
        return

    offset = start

    while offset < end:
        remaining = end - offset
        if remaining < 8:
            model.warnings.append(
                f"Trailing or truncated chunk header at offset 0x{offset:X} "
                f"({remaining} byte(s) remain)."
            )
            return

        chunk_id = data[offset : offset + 4]
        declared_size = struct.unpack_from(">I", data, offset + 4)[0]
        payload_start = offset + 8
        declared_end = payload_start + declared_size
        payload_end = min(declared_end, end)
        actual_size = max(0, payload_end - payload_start)

        name = _decode_tag(chunk_id)
        form_type = ""
        if chunk_id == b"FORM" and actual_size >= 4:
            form_type = _decode_tag(data[payload_start : payload_start + 4])

        model.chunks.append(
            ChunkInfo(
                name=name,
                declared_size=declared_size,
                actual_size=actual_size,
                offset=offset,
                payload_offset=payload_start,
                depth=depth,
                form_type=form_type,
            )
        )

        if declared_end > end:
            model.warnings.append(
                f"Chunk {name} at offset 0x{offset:X} declares {declared_size} "
                f"bytes but only {actual_size} are available."
            )

        payload = data[payload_start:payload_end]
        if chunk_id in payloads:
            payloads[chunk_id].append((payload, payload_start, actual_size))

        if chunk_id == b"FORM":
            if actual_size < 4:
                model.warnings.append(
                    f"FORM chunk at offset 0x{offset:X} has no complete form type."
                )
            else:
                _parse_chunk_stream(
                    data=data,
                    start=payload_start + 4,
                    end=payload_end,
                    depth=depth + 1,
                    model=model,
                    payloads=payloads,
                )

        if declared_end >= end:
            return

        next_offset = declared_end + (declared_size & 1)
        if next_offset <= offset:
            model.warnings.append(f"Invalid chunk size at offset 0x{offset:X}.")
            return
        offset = min(next_offset, end)


def _first_payload(
    payloads: dict[bytes, list[tuple[bytes, int, int]]], chunk_id: bytes, model: SkltModel
) -> tuple[bytes, int, int] | None:
    found = payloads[chunk_id]
    if len(found) > 1:
        model.warnings.append(
            f"Multiple {_decode_tag(chunk_id)} chunks found; only the first is used."
        )
    return found[0] if found else None


def _parse_point_chunk(payload: bytes, chunk_name: str, warnings: list[str]) -> list[Point3D]:
    """Parse POO2/SEN2 points: three big-endian floats, 12 bytes per point."""

    usable_size = len(payload) - (len(payload) % 12)
    if usable_size != len(payload):
        warnings.append(
            f"{chunk_name} size {len(payload)} is not a multiple of 12; "
            f"{len(payload) - usable_size} trailing byte(s) were ignored."
        )

    points: list[Point3D] = []
    for point_index, (x, y, z) in enumerate(struct.iter_unpack(">fff", payload[:usable_size])):
        if not all(math.isfinite(value) for value in (x, y, z)):
            warnings.append(
                f"{chunk_name} point {point_index} contains a non-finite coordinate; "
                "it was replaced with (0, 0, 0)."
            )
            points.append((0.0, 0.0, 0.0))
        else:
            points.append((x, y, z))
    return points


def _parse_legacy_point_chunk(payload: bytes, chunk_name: str,
                              warnings: list[str]) -> list[Point3D]:
    """Parse legacy POOL/SENS points: three big-endian int16, 6 bytes each."""

    usable_size = len(payload) - (len(payload) % 6)
    if usable_size != len(payload):
        warnings.append(
            f"{chunk_name} size {len(payload)} is not a multiple of 6; "
            f"{len(payload) - usable_size} trailing byte(s) were ignored."
        )
    return [
        (float(x), float(y), float(z))
        for x, y, z in struct.iter_unpack(">hhh", payload[:usable_size])
    ]


def _parse_legacy_poly(payload: bytes, warnings: list[str]) -> list[Polygon]:
    """Parse legacy POLY: int16 vertex indices, -1 terminates each polygon."""

    usable_size = len(payload) - (len(payload) % 2)
    if usable_size != len(payload):
        warnings.append("POLY has a trailing odd byte; it was ignored.")
    polygons: list[Polygon] = []
    current: Polygon = []
    for (value,) in struct.iter_unpack(">h", payload[:usable_size]):
        if value == -1:
            polygons.append(current)
            current = []
        else:
            current.append(value)
    if current:
        warnings.append(
            "POLY ends without a -1 terminator; the last polygon was kept."
        )
        polygons.append(current)
    return polygons


def _parse_pol2(payload: bytes, warnings: list[str]) -> list[Polygon]:
    """Parse POL2's polygon count and variable-length uint16 index lists."""

    if len(payload) < 4:
        warnings.append("POL2 is too short to contain its polygon count.")
        return []

    declared_count = struct.unpack_from(">I", payload, 0)[0]
    maximum_possible = (len(payload) - 4) // 2
    polygon_limit = min(declared_count, maximum_possible)
    if declared_count > maximum_possible:
        warnings.append(
            f"POL2 declares {declared_count} polygons, but its size can contain "
            f"at most {maximum_possible} polygon headers."
        )

    polygons: list[Polygon] = []
    offset = 4
    for polygon_index in range(polygon_limit):
        if offset + 2 > len(payload):
            warnings.append(f"POL2 polygon {polygon_index} has a truncated header.")
            break

        vertex_count = struct.unpack_from(">H", payload, offset)[0]
        offset += 2
        index_bytes = vertex_count * 2
        if offset + index_bytes > len(payload):
            warnings.append(
                f"POL2 polygon {polygon_index} declares {vertex_count} indices, "
                "but its data is truncated; the polygon was skipped."
            )
            break

        polygon = list(struct.unpack_from(f">{vertex_count}H", payload, offset)) if vertex_count else []
        offset += index_bytes
        polygons.append(polygon)

    if len(polygons) < declared_count:
        warnings.append(
            f"POL2 parsed {len(polygons)} of {declared_count} declared polygon(s)."
        )
    if offset < len(payload):
        warnings.append(f"POL2 contains {len(payload) - offset} unused trailing byte(s).")

    return polygons


def _validate_polygons(
    polygons: Iterable[Polygon], point_count: int, warnings: list[str]
) -> list[Polygon]:
    # POL2 list positions are persistent polyIDs referenced by BASE/ATTS.
    # Never compact this list when a malformed record is encountered: doing
    # so would silently apply every later material/UV entry to the wrong face.
    # An empty placeholder is safe because both viewers already skip
    # non-renderable polygons while the original on-disk index is preserved.
    validated_polygons: list[Polygon] = []

    for polygon_index, polygon in enumerate(polygons):
        invalid_indices = [index for index in polygon if index >= point_count]
        if invalid_indices:
            warnings.append(
                f"POL2 polygon {polygon_index} references point index "
                f"{invalid_indices[0]}, but POO2 contains {point_count} point(s); "
                "an empty polyID placeholder was kept."
            )
            validated_polygons.append([])
            continue
        if len(polygon) < 2:
            warnings.append(
                f"POL2 polygon {polygon_index} has fewer than two vertices; "
                "it cannot be rendered, but its polyID was preserved."
            )
            validated_polygons.append([])
            continue
        validated_polygons.append(polygon)

    return validated_polygons


def _parse_otl2(payload: bytes, warnings: list[str]) -> list[Point2D]:
    """Parse OTL2 outline points: unsigned byte x,y pairs."""

    usable_size = len(payload) - (len(payload) % 2)
    if usable_size != len(payload):
        warnings.append(
            f"OTL2 size {len(payload)} is not a multiple of 2; "
            f"{len(payload) - usable_size} trailing byte(s) were ignored."
        )

    points: list[Point2D] = []
    for offset in range(0, usable_size, 2):
        points.append((payload[offset], payload[offset + 1]))
    return points


def _parse_olpl(payload: bytes, warnings: list[str]) -> list[OutlineGroup]:
    """Parse OLPL as 2D outline groups referencing OTL2 point indices.

    Each group is stored as a big-endian uint16 index count followed by that
    many big-endian uint16 OTL2 point indices.
    """

    groups: list[OutlineGroup] = []
    offset = 0
    group_index = 0

    while offset < len(payload):
        if offset + 2 > len(payload):
            warnings.append(f"OLPL group {group_index} has a truncated header.")
            break

        index_count = struct.unpack_from(">H", payload, offset)[0]
        offset += 2
        index_bytes = index_count * 2

        if offset + index_bytes > len(payload):
            warnings.append(
                f"OLPL group {group_index} declares {index_count} indices, "
                "but its data is truncated; the group was skipped."
            )
            break

        if index_count:
            groups.append(list(struct.unpack_from(f">{index_count}H", payload, offset)))
        else:
            groups.append([])

        offset += index_bytes
        group_index += 1

    return groups


def _validate_outline_groups(
    groups: Iterable[OutlineGroup], point_count: int, warnings: list[str]
) -> list[OutlineGroup]:
    valid_groups: list[OutlineGroup] = []

    for group_index, group in enumerate(groups):
        invalid_indices = [index for index in group if index >= point_count]
        if invalid_indices:
            warnings.append(
                f"OLPL group {group_index} references OTL2 point index "
                f"{invalid_indices[0]}, but OTL2 contains {point_count} point(s); "
                "the group was skipped."
            )
            continue
        if len(group) < 2:
            warnings.append(
                f"OLPL group {group_index} has fewer than two points; "
                "it cannot be rendered."
            )
            continue
        valid_groups.append(group)

    return valid_groups


def _encode_poo2(points: list[Point3D]) -> bytes:
    encoded = bytearray()
    for point in points:
        x, y, z = point
        if not all(math.isfinite(value) for value in (x, y, z)):
            raise SkltParseError("POO2 coordinates must be finite float values.")
        encoded.extend(struct.pack(">fff", x, y, z))
    return bytes(encoded)


def _encode_pol2(polygons: list[Polygon], point_count: int) -> bytes:
    encoded = bytearray()
    encoded.extend(struct.pack(">I", len(polygons)))
    for polygon_index, polygon in enumerate(polygons):
        # Original assets use zero-length POL2 records as stable polyID
        # placeholders.  Preserve them during structural saves; a one-vertex
        # record is still rejected because it is neither a valid face nor a
        # known placeholder convention.
        if len(polygon) == 1:
            raise SkltParseError(
                f"POL2 polygon {polygon_index} has exactly one vertex."
            )
        if len(polygon) > 0xFFFF:
            raise SkltParseError(
                f"POL2 polygon {polygon_index} has too many vertex indices."
            )
        for point_index in polygon:
            if point_index < 0 or point_index >= point_count:
                raise SkltParseError(
                    f"POL2 polygon {polygon_index} references invalid point "
                    f"index {point_index}."
                )
        encoded.extend(struct.pack(">H", len(polygon)))
        encoded.extend(struct.pack(f">{len(polygon)}H", *polygon))
    return bytes(encoded)


def _rewrite_first_chunk_payloads(data: bytes, replacements: dict[bytes, bytes]) -> bytes:
    used = {chunk_id: False for chunk_id in replacements}

    def rewrite_stream(start: int, end: int, depth: int) -> bytes:
        if depth > MAX_FORM_DEPTH:
            raise SkltParseError("FORM nesting exceeds the safe save limit.")

        output = bytearray()
        offset = start
        while offset < end:
            if end - offset < 8:
                raise SkltParseError(
                    f"Cannot save structurally: truncated chunk header at 0x{offset:X}."
                )

            chunk_id = data[offset : offset + 4]
            declared_size = struct.unpack_from(">I", data, offset + 4)[0]
            payload_start = offset + 8
            payload_end = payload_start + declared_size
            if payload_end > end:
                raise SkltParseError(
                    f"Cannot save structurally: chunk {_decode_tag(chunk_id)} at "
                    f"0x{offset:X} extends past its container."
                )

            old_payload = data[payload_start:payload_end]
            if chunk_id == b"FORM":
                if declared_size < 4:
                    raise SkltParseError("Cannot save structurally: malformed FORM chunk.")
                form_type = old_payload[:4]
                children = rewrite_stream(payload_start + 4, payload_end, depth + 1)
                new_payload = form_type + children
            elif chunk_id in replacements and not used[chunk_id]:
                new_payload = replacements[chunk_id]
                used[chunk_id] = True
            else:
                new_payload = old_payload

            output.extend(chunk_id)
            output.extend(struct.pack(">I", len(new_payload)))
            output.extend(new_payload)

            old_padding_offset = payload_end
            old_has_padding = bool(declared_size & 1)
            payload_unchanged = new_payload == old_payload
            if len(new_payload) & 1:
                if payload_unchanged and old_has_padding and old_padding_offset < len(data):
                    output.append(data[old_padding_offset])
                else:
                    output.append(0)

            offset = payload_end + (declared_size & 1)

        return bytes(output)

    rewritten = rewrite_stream(0, len(data), 0)
    missing = [_decode_tag(chunk_id) for chunk_id, was_used in used.items() if not was_used]
    if missing:
        raise SkltParseError(f"Cannot save structurally: missing {', '.join(missing)} chunk.")
    return rewritten



def _clamp_byte(value: int) -> int:
    return max(0, min(255, int(value)))


def _decode_tag(tag: bytes) -> str:
    return tag.decode("ascii", errors="replace")
